[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
# risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "775e8be3294a300b7eeff23474d207bfb571c42b" }
risc0-zkvm = { path = "../../risc0/risc0/risc0/zkvm" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
cfdkim = { git = "https://github.com/risc0-labs/dkim" } 
mailparse = "0.14.0"
tokio = { version = "1.41.1", features = ["full"] }
trust-dns-resolver = "0.23.2"
slog = "2.7.0"
anyhow = "1.0.93"
log = "0.4.22"
