[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "775e8be3294a300b7eeff23474d207bfb571c42b" }

[package.metadata.risc0]
methods = ["guest"]
